# Generated by Django 5.2.10 on 2026-01-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumechecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_description',
            field=models.TextField(),
        ),
    ]
