# Generated by Django 5.2.9 on 2026-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumechecker', '0003_registeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
